### ISSUE TITLE
support for ts

### ISSUE THREAD

**Issue by zl810881283** [helapkg/hela#104]
Does koa-better-body take it into consideration that support for typescript(define .d.ts)?

**Comment by xujif** [comment]
+1

**Comment by tunnckoCore** [comment]
prs are welcome. im not familiar with it so much to write it.

**Comment by danwbyrne** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28468

**Comment by tunnckoCore** [comment]
@danwbyrne great, thanks! :tada:

**Comment by tunnckoCore** [comment]
It's now merged, so we can close this one! :100: 

Thanks again.
