### ISSUE TITLE
koa-better-body: todos

### ISSUE THREAD

**Issue by tunnckoCore** [helapkg/hela#12]
- [ ] need more tests?
- [x] examples (use cases)
- [x] beautify tests - separate them?

**Comment by tunnckoCore** [comment]
- [ ] need tests for `opts.extendTypes`

**Comment by bitinn** [comment]
PS: maybe update to `node-formidable` 1.0.17 as well, fix an deprecated message for Buffer.write when multipart support is enabled. see https://github.com/felixge/node-formidable/pull/313

**Comment by tunnckoCore** [comment]
Its `>=1.0.16` now so.. but yea, in next commits.

**Comment by booxood** [comment]
Looking forward to the new version. : )

**Comment by tunnckoCore** [comment]
What you are looking for exactly? :)

PRs welcome for this todos.

**Comment by booxood** [comment]
As the above said, have a warn message.
If update node-formidable to 1.0.17, the package will be **better**.

**Comment by tunnckoCore** [comment]
hoho.. need to remind him to publish it to npm.. @felixge

**Comment by tunnckoCore** [comment]
I revert it back to `~1.0.16` range, because the `~` which will install latest patch available. :)
So all is okey.

**Comment by tunnckoCore** [comment]
@booxood @bitinn released and published as `v1.0.17`

**Comment by booxood** [comment]
:+1:

**Comment by dan-dr** [comment]
co-body is seriously outdated. uses an old version of qs. also qs exposes options which co-body doesn't.
i'll look into making co-better-body which only upgrades the dependencies and exposes options.
