### ISSUE TITLE
koa deprecated Support for generators will be removed in v3.

### ISSUE THREAD

**Issue by qiulang** [helapkg/hela#166]
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md

Can you update your codes ?

Thanks!

**Comment by tunnckoCore** [comment]
Yea, I know, thanks. Is it known when v3 will be released? To know what time I have for v4 of this package.

**Comment by qiulang** [comment]
https://github.com/koajs/koa/issues/1114 talks about 3.0 roadmap.

**Comment by tunnckoCore** [comment]
And still, they are at 2.7.

I'm following and will update it when it happens.
