### ISSUE TITLE
How to save uploaded files in folder which name is session id in cookie?

### ISSUE THREAD

**Issue by budarin** [helapkg/hela#169]
HI!

Default settings dont willing me to have an access to ctx in formidable foem event handlers.
How to set path to folder which name is session id from cookie?

**Comment by tunnckoCore** [comment]
You can move the file. That's the current situation, because for the uploading we relying on Formidable, which has dozen of problems regarding similar cases. I'm sorry about that. There we have few issues with some workarounds, you can check them :)
