### ISSUE TITLE
koa-body-parser version using git url

### ISSUE THREAD

**Issue by antoinegomez** [helapkg/hela#170]
Hello,

Using a docker image without git installed I encountered an error installing koa-better-body that links to a version of koa-body-parsers using a git url instead of a version.

This also looks like it will always fetch the latest version. Shouldn't be safer to have at least a version matching pattern to avoid getting BC ?

Anyway it's annoying to have to install git only for a npm dependency.

**Comment by tunnckoCore** [comment]
I know, but that was intentional. Thanks anyway.

duplicate #107
