### ISSUE TITLE
it doesn't work with latest egg.js

### ISSUE THREAD

**Issue by nicetomeetnode** [helapkg/hela#215]
i close egg.js default bodyparser in config.default.js

 config.bodyParse = {
    enable: false,
  }

and then i import koa-better-body in config.default.js

const convert=require("koa-convert");
module.exports = convert(require('koa-better-body'));

config.middleware = ["koaBetterBody"]

but it doesn't work when i set hearder application/json to post a json

**Comment by tunnckoCore** [comment]
Heya, @nicetomeetnode 

This package wasn't touched in years. So if it was working before this "latest" version of egg.js, then it's problem there in this exact "latest" version.
