### ISSUE TITLE
Cant parse array data properly (send via `FromData`)

### ISSUE THREAD

**Issue by creeperyang** [helapkg/hela#26]
Data will be like this:

```
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryUzoXapxqkoPvr8T2

...

------WebKitFormBoundaryUzoXapxqkoPvr8T2
Content-Disposition: form-data; name="tags[]"

569899aad67fa76e5ad3d663
------WebKitFormBoundaryUzoXapxqkoPvr8T2
Content-Disposition: form-data; name="tags[]"

569899aad67fa76e5ad3d664

...
```

And `better-body` only get one item of `tags[]`, I mean the parsed data will be like this:

``` js
fields: {
   'tags[]': '569899aad67fa76e5ad3d664'
}
```

Maybe the lib(`formidable`) just **overwrite** the `tags[]`, and cant handle array notation properly.

**Comment by tunnckoCore** [comment]
Should be resolved. Need more tests #32 - they will be added soon (before v2). More at https://github.com/tunnckoCore/koa-better-body/pull/34
