### ISSUE TITLE
Give user the way to register `formidable` events and so they can deal with file uploading

### ISSUE THREAD

**Issue by creeperyang** [helapkg/hela#27]
Sometimes we need to rename file(set file path) dynamically, so it's important to give a way to interact with `formidable`. (Current formidable options are not enough.)

**Demo:**

```
// upload Blob
------WebKitFormBoundaryi8ZhzSYa1jK76hJC
Content-Disposition: form-data; name="tags"

56a1f2c06dfc44c4570a46cb,56a1f2c06dfc44c4570a46cc
------WebKitFormBoundaryi8ZhzSYa1jK76hJC
Content-Disposition: form-data; name="headImg"; filename="blob"
Content-Type: image/jpeg


------WebKitFormBoundaryi8ZhzSYa1jK76hJC--
```

Here I have to register `fileBegin` event to add extension to filename:

``` js
form.on('fileBegin', function(name, file) {
    file.name = xxxx; // add ext to file.name, retrive ext from file.type
    file.path = xxxx; // add ext
});
```

**Comment by tunnckoCore** [comment]
Good idea. I definitely should return back to these `koa-*` libs.

Sorry for the delay and for the outdating, but.

**Comment by tunnckoCore** [comment]
@creeperyang Thanks for the idea and the PR.

PRs always welcome, if you can help with v2 milestone it would be great.
