### ISSUE TITLE
Why you use this module? (next release discussion)

### ISSUE THREAD

**Issue by tunnckoCore** [helapkg/hela#29]
/cc @creeperyang @isdenya @daiwhea and any other who use it.

I'm curious, why? Because the `formidable` (maybe this is the only middleware that uses formidable) or because some other thing?

**Comment by creeperyang** [comment]
Maybe the integration and convenience.

**Comment by tunnckoCore** [comment]
Hm. I'm asking because `formidable` looks too outdated to me and maybe not worth using it.
At all, I like it, but I'm not sure that today it is so fast as before so much months (years), there's no actual benchmarks and new core changes + too much issues. I like that it provides option to limit the "max file size", byte size and etc, but.. I don't know, `busboy` seems more stable fluent api and compatible with todays things, promises and etc.
I'm thinking to use `koa-body-parsers` in the background and provide almost the same interface as current - almost no breaking changes. `koa-body-parsers` need wrapping, cuz it not handles automatically request bodies and everyone should play with multipart things. Using it would low the codebase and would have better and sane defaults.
Or I can think to create wrapper for `(co-)busboy` after deep review.

**Comment by tunnckoCore** [comment]
@creeperyang, and others of course, v2 is almost here! :) You can see the [refactor branch](https://github.com/tunnckoCore/koa-better-body/tree/refactor)!
