### ISSUE TITLE
pre v2.0 - tests, docs, recipes

### ISSUE THREAD

**Issue by tunnckoCore** [helapkg/hela#32]
### tests
- [x] for dlau/koa-body#15 (multiple fields)
- [x] for #26 (array data)
- [x] for options.onerror
- [x] may need to separate them to `test/` dir
### docs
- [x] document `index.js`
- [x] document `utils.js`
- [x] rich readme
### recipes (post-v2)
- [ ] parsing xml body
- [ ] rich examples
- [ ] usage with other middlewares: koa-router, koa-route, koa-resource, more
- [ ] koa@2 way
- [ ] jsonStrict and non-strict
- [ ] extendTypes
- [ ] onerror
- [x] multipart: custom `files` and `fields` names
- [x] formidable.IncomingForm instance: events handling

Plans for `koa@2` support by default, if you don't want to use `koa-convert`. Maybe v2.2 or v3.

**Comment by tunnckoCore** [comment]
@zhoul-HS @carlitux @pepkin88 @creeperyang @tyler46 @daiwhea @ipeisong @amcnamara @joeybloggs @sedenardi 

Hi guys! We can start doing "recipes". :) If you want to help and have time - PRs welcome! I started with `multipart`, you can follow it. I also am very excited to hear feedback for the [refactor (compare)](https://github.com/tunnckoCore/koa-better-body/compare/refactor) branch or the #32 PR that I created for it. I think it looks fantastic and awesome.

**Comment by creeperyang** [comment]
@tunnckoCore I'd like to help with `formidable.IncomingForm instance: events handling`.

**Comment by tunnckoCore** [comment]
@creeperyang great! I'll wait PR. 

Make a directory `recipes/formidable` and in README set some examples and text, help, tips and tricks. I look to recipes as kind of test cases, but in human language, tricks, can be in form of FAQ if you want. Also examples from the readme should exist as `.js` files which should work. 

Don't mind if it is in separate commits or in one commit, it's not a problem to me.

I'll finish the `recipes/multipart` which I think to handle uploading files, fields handled by formidable (a.k.a multipart/form-data, because package also can accept urlencoded body), and showing how works custom `fields` and `files` property names (e.g. `options.fields: 'foobar'` then it would be `this.request.foobar` instead of default `this.request.fields`.

_Thanks again! Is todo list clean enough, is understandable enough? If someone have questions - ask, no problem. If someone have more ideas for recipes - PRs welcome!_

I'm thinking to release v2 tonight with one or two recipes, others after that.

Cheers,
Charlike!

**Comment by tunnckoCore** [comment]
I'm excited to see `formidable` recipe, because have a bad feeling that it can have some problem there, not sure enough. Also the tests for event handling are needed.

**Comment by sedenardi** [comment]
@tunnckoCore I can add a recipe for a blank post, but I'm not sure how useful that will be for users of the package.

**Comment by tunnckoCore** [comment]
@sedenardi mm yea it's in the todo list as `jsonStrict and strict mode` point. Most of the recipes listed currently as ideas are existing as tests - strict and non-strict mode are in `test/options.js` file, you can check it. :)

Go create a recipe, it would be useful in anyway. :+1: I'm not sure for the name, but maybe `recipes/strict-mode` make sense, `jsonStrict` is for another recipe. :) I didn't get the idea of recipes to now, because I'm type of developer/person which always fully read the readme then fully read the tests and it completely enough for me, but there are another kind of persons that not reads the tests and see more value on "recipes".

edit: it would be useful. we should answer what is strict mode and what is non-strict mode, and why it exists, what are the diffs and link/mention IETF draft.

Thanks to you too.

**Comment by sedenardi** [comment]
@tunnckoCore Got it. Will try to find some time this week and send it over.

**Comment by tunnckoCore** [comment]
Great!

[Contributing guide for recipes](https://github.com/tunnckoCore/koa-better-body/tree/refactor#contributing-recipes) may help more. :)

**Comment by creeperyang** [comment]
@tunnckoCore Please see #36 and check if qualified.

**Comment by tunnckoCore** [comment]
I'm just continuing the todo list for later today:
- [ ] when `IncomingForm` instance is passed to `options`, you should be able to pass IncomingForm options to that `options`. For example (pseudo-code)

``` js
var form = new IncomingForm()
form.on('file', console.log)

app.use(body({
  IncomingForm: form,
  keepExtensions: true,
  uploadDir: path.join(__dirname, 'uploads')
}))
```

instead of these two ways of doing it

**first**

``` js
var form = new IncomingForm({
  keepExtensions: true
  // etc
})
```

**second (as in recipe and as in formidable README)**

``` js
var form = new IncomingForm()
form.keepExtensions = true
```
- [ ] test cases

**Comment by tunnckoCore** [comment]
- [x] should submit PR for https://github.com/koajs/body-parsers/issues/19

**Comment by tunnckoCore** [comment]
closing this. I'll open new one for recipes.

**Comment by tunnckoCore** [comment]
It's there guys, the awesome `v2` :) Also publish on npm!
