### ISSUE TITLE
stopped getting 404 on post/put/patch requsts

### ISSUE THREAD

**Issue by codeinvain** [helapkg/hela#42]
context.body (which alias  **response**.body) is automatically assigned with parsed value of **request**.body 
see  https://github.com/tunnckoCore/koa-better-body/blob/master/utils.js#L188

setting the **response**.body  causes koa to return a json response with parsed body parameters for every PATCH/PUT/POST  instead of throwing 404 not found when no route is defined.

-- edit -- 
applies to v2.0

**Comment by tunnckoCore** [comment]
I believe it isn't `koa-better-body` problem, but can you give some actual example, or the best will be to submit a PR with test case for it.

**Comment by codeinvain** [comment]
thanks for your thought on that, if you don't think it's koa-better-body problem's then it's all good , just note that koa sets the status to 200 if you assign value to response.body  https://github.com/koajs/koa/blob/master/lib/response.js#L142

best,
d.

**Comment by tunnckoCore** [comment]
Don't get me wrong. I just don't get the problem and why router thing should be related to this module.
What can be the fix, if it is related to this package? Can you give some example to visualize the thing?

I'm open to help, but I can't get it currently.

**Comment by tunnckoCore** [comment]
I mean, how downstream middleware can know what upstream does? Do you have "catch all" route to handle the 404. Something like

``` js

app
.use('/foo', foo)
.use('/bar', bar)
.use('/baz', baz)
.use('*', function () {
  this.status = 404
  this.body = 'Not Found'
})
```

As I remember koa have 404 handler by default?

I don't know, give some code, please. :)

edit: if you have route for 404 case (when the incoming request is not any of the defined routes) then there's no logic to come to body parser?

**Comment by codeinvain** [comment]
```
let Koa = require('koa')
let body = require('koa-better-body')
let koa = new Koa()
koa.use(body())
koa.use(function *test(){
  console.log(this.path)
  console.log(this.body)
})
koa.listen(5000);
```

try comment/uncomment koa-better-body (line 5) and use the curl bellow
`curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -F "name=codeinvain" "http://localhost:5000/it_should_return_404"
`

**Comment by tunnckoCore** [comment]
The parser behind fails and result is `Internal Server Error`. Please do a PR and we see and can do something, I can't do nothing.

**Comment by tunnckoCore** [comment]
[The best issue report is a failing test proving it.](https://twitter.com/sindresorhus/status/579306280495357953)

**Comment by codeinvain** [comment]
@tunnckoCore  I'm not working with this package, i had to evaluate it for a client and decided not to used it based on this unexpected behaviour. 
I opened the ticket to let you (and whom ever wants to use this package) to know, and maybe to to understand the logic behind setting **response**.body with request body content

best,
d.

**Comment by tunnckoCore** [comment]
@codeinvain can you try with latest master (or upcoming v2.1 - will publish in a bit)?
I believe problem may be fixed with https://github.com/tunnckoCore/koa-better-body/commit/b927454ad922b8f80fa4057e00644d36f16826f9 (which fixed #50)

**Comment by paullryan** [comment]
@tunnckoCore #50 does not seem to fix this and I agree with codeinvain that you should not be setting this.body to the fields automatically this causes some weird behaviors with the way other koa modules expect body to behave, this.body (or ctx.body in 2+) should only be set with a completed request which is up to our applications use case.

**Comment by paullryan** [comment]
@tunnckoCore Nevermind my previous comment, must have installed master incorrect, just verified that https://github.com/tunnckoCore/koa-better-body/commit/b927454ad922b8f80fa4057e00644d36f16826f9 fixes this issue and leaves this.body (ctx.body) alone.

**Comment by tunnckoCore** [comment]
@paullryan great to hear, thanks! @codeinvain so we can close this one? And I'll publish v2.1.

**Comment by tunnckoCore** [comment]
So we can close this one. :)
