### ISSUE TITLE
Support qs syntax?

### ISSUE THREAD

**Issue by EvanCarroll** [helapkg/hela#45]
It'd be nice if the input names supported [qs syntax](https://www.npmjs.com/package/qs#readme) so `<input name="foo.bar" value="quz">` and `<input name="foo[bar]" value="quz>` would set

```
this.request.foo.bar = quz
```

This is supported in the regular [body-parser](https://github.com/expressjs/body-parser).

> _extended_ the extended option allows to choose between parsing the URL-encoded data with the querystring library (when false) or the qs library (when true). The "extended" syntax allows for rich objects and arrays to be encoded into the URL-encoded format, allowing for a JSON-like experience with URL-encoded. For more information, please see the qs library.

**Comment by tunnckoCore** [comment]
You can pass what you want to `app.querystring` - see [koa-body-parsers/index.js#L53](https://github.com/koajs/body-parsers/blob/master/index.js#L53).

Is that enough?

``` js
var qs = require('qs')
var koa = require('koa')
var app = koa()

app.querystring = qs
app.use(body())
```

i believe?

**Comment by tunnckoCore** [comment]
@EvanCarroll let me know if not works.

It also would be great to have test for that case, PRs welcome by everyone.

**Comment by tunnckoCore** [comment]
Proofs that works before, now and in future https://github.com/tunnckoCore/koa-better-body/commit/c5df3a3659caa1819f158448c514a61e26d22302

**Comment by EvanCarroll** [comment]
ahh, or alternatively,

```
var app = koa().use(betterBody({
   querystring: require('qs')
}))
```

**Comment by tunnckoCore** [comment]
Yeah, exactly. It works. :) Looks great, i have only some bits to update - changelog and some boilerplate stuff and will publish v3 soon.
