### ISSUE TITLE
how to set upload dir?

### ISSUE THREAD

**Issue by lrbmike** [helapkg/hela#47]
with koa-body, we can set the upload dir like this:
`var app      = require('koa')(),
    koaBody   = require('koa-body');

app.use(koaBody({formidable:{uploadDir: __dirname}}));`

but with this middleware, it's not working. it upload to '/var/folders/....'
how can i set the upload dir

**Comment by lrbmike** [comment]
i have found the solution, just like this:
`app.use(body({uploadDir: './public/upload'}));`

**Comment by tunnckoCore** [comment]
Yea, because initially I built both middlewares and they were similar before #34 (v2). In v2 you can pass all formidable options directly, not through `formidable` prop :)

It's always enough to read carefully the readme and look the recipes :)

Cheers.
