### ISSUE TITLE
How to store different type files in different dir?

### ISSUE THREAD

**Issue by hezhongfeng** [helapkg/hela#48]
For example:

```
//ajax's url
url: '/upload/images'
```

And I want to store it in uploads/images dir.

Another one:

```
//ajax's url
url: '/upload/films'
```

And I want to store it in uploads/films dir.

Now I used it this way,and whatever type it is,It will store in uploads dir.

```
app.use(convert(body({
       encoding: 'utf-8',
       uploadDir: path.join(__dirname, 'uploads'),
       keepExtensions: true
    })))
```

How can I do to store different type files in different dir?

**Comment by hezhongfeng** [comment]
And how to set the file's name?
I'm afraid to create a same name file.

**Comment by tunnckoCore** [comment]
All of this is formidable-related questions and i'm not very familiar with it. But there's a way to control and do whatever you want through the `options.IncomingForm` option. All `options` from here are directly passed to formidable (more specific, to IncomingForm).

Search formidable issues and PRs and look deeper at its docs. :)

**Comment by hezhongfeng** [comment]
@tunnckoCore 
Thank you for your answer.
I used nodejs file system to delete the file.
