### ISSUE TITLE
Koa v2

### ISSUE THREAD

**Issue by LaurensRietveld** [helapkg/hela#49]
The `README.md` file shows:

```
Full-featured koa body parser! Support parsing text, buffer, json, json patch, json api, csp-report, multipart, form and urlencoded bodies. Works for koa@1, koa@2 and will work for koa@3.
```

I was a bit confused by this message. Is there a koa@3, and does this lib really work for koa@2?
In my case, I had to use `koa-convert` to get this working for koa-2 and koa-router

**Comment by tunnckoCore** [comment]
There's no koa@3, but it will work cuz koa@2 style will be the future in anyway. And yes, you should use koa-convert. I just don't see the point to convert it to be v2-compatible and hit koa@1 users, when there's koa-convert.

edit: PR welcome to add this notice if not so clear.
