### ISSUE TITLE
A few ideas: options.extendTypes.custom, options.handler, split buffer thingy?

### ISSUE THREAD

**Issue by tunnckoCore** [helapkg/hela#52]
Get an ideas.
### split buffer thingy

Currently (in v2.0):
- if you wanna buffer body, you should pass `options.buffer: true` and trick the things through `options.extendTypes.text` (because that's the only way to use the `this.request.buffer` parser to parse buffers). you will receive it in `this.request.body`
- If you wanna limit the buffer size you should pass `options.textLimit` or `options.bufferLimit`

I'm asking myself, isn't it will be better if there's separate `if` for `options.extendTypes.buffer` and try to parse it separate from text? So i came to the next idea for `extendTypes.custom`
### options.extendTypes.custom and options.handler

So, to be able hack the things legally. Meaning if you wanna parse `foo/bar-x` type, for instance, you will pass that type to `options.extendTypes.custom: ['foo/bar-x']`, then `options.handler.call(ctx, ctx, options, next)` will be called.

_related: #22 and #31_

This will give you the freedom and ability to do whatever you want:
1. access the `this` context (`ctx`)
2. access the original options (`options`)
3. to use all of the parsers - `ctx.request.json`, `ctx.request.urlencoded`, `ctx.request.multipart`, `ctx.request.text` and `ctx.request.buffer`
4. and what your mind can think

**Comment by tunnckoCore** [comment]
@codeinvain, @ztrange, @LaurensRietveld, @internalfx, @creeperyang  and @daiwhea, thoughts?

**Comment by ztrange** [comment]
It sounds cool!

On an unrelated matter, since you stopped using this.body, I think the major version (semver) should be bumped, since it is a breaking change.

**Comment by internalfx** [comment]
@ztrange I agree.

@tunnckoCore I think these are great additions. However, they are _very_ likely to break existing apps.

**Comment by tunnckoCore** [comment]
@ztrange, i'm not sure enough. in one side, it is bugfix to wrong behaviour - it was total mistake, in  another yea it is breaking change, but dont thinking for major bump, but for minor definitely.

about the ideas, i'll try to push them today.

**Comment by tunnckoCore** [comment]
but yea maybe you are right, i'll add these features and bump major directly

**Comment by tunnckoCore** [comment]
All is implemented as suggested.
