### ISSUE TITLE
When i try to upload multiple files

### ISSUE THREAD

**Issue by IOsonoTAN** [helapkg/hela#55]
I try to upload multiple files with this code..
`<input type="file" name="files" multiple="true">`

It's incorrect format, I think it should be array under files field.
![screen shot 2559-08-12 at 11 46 45 pm](https://cloud.githubusercontent.com/assets/3783531/17629985/8bbe8898-60e7-11e6-91d9-a08c8ab0d41b.jpg)

Thanks

**Comment by tunnckoCore** [comment]
Seems wrong, yea. But can you post your code or something more.

**Comment by IOsonoTAN** [comment]
This problem will appear when upload files more than two files.

In app.js is the main of my project

```
const koaBetterBody = require('koa-better-body')
app.use(koaBetterBody())
```

In HTML

```
<form method="POST" enctype="multipart/form-data">
  <input type="file" name="files" multiple="true">
  <input type="submit">
</form>
```

In controller

```
this.body = {
  files: this.request.fields
}
```

**Comment by IOsonoTAN** [comment]
I try to fix handleFilesAndFields's function in utils.js from

```
res[name] = res[name] ? [res[name]] : []
res[name].push(value)
res[name] = res[name].length > 1 ? res[name] : res[name][0]
```

to

```
res[name] = res[name] ? res[name] : []
if(typeof value === 'object') (value.size > 0 ? res[name].push(value) : null)
else {
  if(!res[name][0]) res[name] = value
  else {
    res[name] = [res[name]]
    res[name].push(value)
  }
}
```

it works :)

**Comment by tunnckoCore** [comment]
You do it wrong. You pass `this.request.fields`, but they are on `this.request.files` logically. :) Try that and report back. :)

**Comment by tunnckoCore** [comment]
If the form is like that

``` html
<form method="POST" enctype="multipart/form-data">
  <input type="file" name="files" multiple="true">
  <input type="text" name="foo">
  <input type="text" name="bar">
  <input type="submit">
</form>
```

Files will be on `this.request.files` and the `foo` and `bar` fields will be in `this.request.fields` - so `this.request.fields.foo` and `this.request.fields.bar`, got it?

**Comment by tunnckoCore** [comment]
I think now everything is solved :) It is more flexible, more stable than ever. Follow the CHANGELOG.

**Comment by IOsonoTAN** [comment]
Oh that's good news :)

Thanks for fixing the issue

**Comment by tunnckoCore** [comment]
Yea, you was right :) I think v3 now is awesome?
