### ISSUE TITLE
Unable to access files when fieldsKey is set to false

### ISSUE THREAD

**Issue by pepkin88** [helapkg/hela#6]
In the code is a fragment:

```
if (typeof opts.fieldsKey !== 'string') {
  copy = copy.fields
} else {
```

which means that information about files is deleted. What was the reasoning behind this? Earlier there was an option `filesKey`, why was it removed? Could this new behavior be reverted, so that it is possible to access uploaded files?

**Comment by tunnckoCore** [comment]
Im not sure whats the problem is. Yea `filesKey` was removed, because I think it is convention to find files in something named `files` and its not a good idea to named it differently.
Files can be found in `body.files` always.

**Comment by tunnckoCore** [comment]
Hmm, got it. Strange, tests pass... huh.

I'll do something ASAP. PRs welcome

**Comment by tunnckoCore** [comment]
@pepkin88 If you dont want to be something different than `fields` (actually string) just not set it.
This check is intentional, actually. It always will return object with `files` and `fields` properties if `fieldsKey` is string - it is by default, and if provided in opts it should be string.

At all, the logic behind this is that you may not want to have `fields` / `files` properties, just the names of the form. Say you have form with names `username`, `password`, `image`, `city` etc, and  you want them directly in `this.body` (`this.body.username`, `this.body.password`, `this.body.city`), than you should set fieldsKey to `false` - with that you say _"i want them directly, not (false) in specific fields key"_

So default behavior is object with files and fields properties.

More clarification? :)

**Comment by pepkin88** [comment]
Yes, I want all fields to be directly set to `this.request.body`, as it is an existing convention. In #1 the parsed fields were used by passport, but there are more modules that use this convention, such as koa-csrf, which I'm using.
And also, frankly, I find splitting fields on text fields and files a bit counter intuitive and not so useful, they are sent together on the same level anyway. So I like the option not to separate text from files, but without having access to uploaded files, this middleware is useless for me (or would be if I didn't rewrite these fields manually).
Could it be enabled in some way? Files could be in `this.request.body.files`, but I think it might be better if they was directly set on `this.request.body`, just like other fields. I don't think the field name collisions are an issue here, because formidable overwrites text fields anyway, so developers know that better use different names for fields. Also, they know the structure of their sent forms, so they know which fields are file fields, no need for distinction and separation. In cases of malicious requests, such where files are sent with a name of a text field, all fields should be checked anyway (or handled in a way, that this isn't a problem). And if they still need it separated, that's ok, since merging text and file fields would be enableable by an option, the default behavior won't change.
What do you think?

**Comment by pepkin88** [comment]
After a while I realized, that it is indeed easier not to worry about a situation, where a file field would appear in a place of a text field (in case of malicious requests). So good options would be setting files  in `this.request.body.files` (or on other key) or directly in `this.request.files`, with semantic meaning of files associated with the request (but with a slight risk of conflicting with other modules). I think either option would be good.

**Comment by tunnckoCore** [comment]
Hmm. Good point.

The solution would be to revert back the option for `filesKey` plus `*handleRequest` to return `request` object instead just body object and using `extend` here

``` js
var data = yield* handleRequest(this, options);

this.request.body = options.patchKoa ? data : null;
this.req.body = options.patchNode ? data : null;
```

PRs welcome :) I will update/merge as soon as possible

**Comment by tunnckoCore** [comment]
[#73d63](https://github.com/tunnckoCore/koa-better-body/blob/73d63a0da278a5b0c8fdc2b735e6b4ab4bbdcc35/index.js) this commit could be remainder

**Comment by tunnckoCore** [comment]
Done. Thanks!
