### ISSUE TITLE
not working with koa-router 

### ISSUE THREAD

**Issue by st0ffern** [helapkg/hela#64]
as the title says

**Comment by tunnckoCore** [comment]
Example or something?! We are not magicians. There are tons of tests. Best proof of an issue is adding failing test.

**Comment by tunnckoCore** [comment]
@stoffern any process?

**Comment by st0ffern** [comment]
nope, and i will not followup on it. 
Since you are not a magician, i am not working for free.. 😉

**Comment by tunnckoCore** [comment]
Sorry but we are open source, we can't work and fix things/issues/bugs that don't understand because submitter don't want to show 5 lines code example.

**Comment by jonathanasquier** [comment]
Hi, I'm also getting a undefined body with the most minimal set up with koa router

```
var koa = require('koa'); //^1.2.4
var router = require('koa-router')();//^5.4.0
var koa_body = require('koa-better-body');//^3.0.0

var app = koa();

router
.post('/mypost',
  koa_body(),
  function *(next) {
    console.log(this.request.body) //undefined
    ...
  }
)

app.use(router.routes());

app.listen(3000);
```

My post has a application/json content type, and I try sending a raw json :/

**Comment by tunnckoCore** [comment]
@jonathanasquier I'll try it, thanks! Maybe something in `koa-router` i'll review.

**Comment by tunnckoCore** [comment]
@jonathanasquier @stoffern who didn't read the docs or at least the code? 

There's no `this.request.body` when multipart.
There's no `this.request.body` when json.
There's no `this.request.body` when urlencoded.

Everything is logically separated to `fields` and `files` in the `this.request` object. You can customize that names for example if you wanna fields from urlencoded forms (not multipart/form-data) to be in `this.request.body` you should pass `options.fields: 'body'` But not make the mistake to pass both `options.fields` and `options.files` to be `'body'` it won't work correctly - only one of them will be written to that `.body` property.

**Comment by tunnckoCore** [comment]
**working example**

``` js
'use strict'

var body = require('./index')

var koa = require('koa')
var router = require('koa-router')()

var app = koa()

router
  .post('/upload', body(), function * (next) {
    console.log(this.request.files)
    console.log(this.request.fields)

    // there's no `.body` when `multipart`,
    // `urlencoded` or `json` request
    console.log(this.request.body)
  })

app.use(router.routes())
app.listen(4292)

var format = require('util').format
var host = 'http://localhost:4292'
console.log(format('curl -i %s/upload -F "source=@%s/.editorconfig"', host, __dirname))
```

I'll finish it a bit and push it to github.

**Comment by jonathanasquier** [comment]
Had a doubt under the shower... what if I just didn't RTFM?
10h late, sorry!

**Comment by tunnckoCore** [comment]
No problems. I don't have such problems, cuz just read few lines of each repository/package. It's a matter of dev and flow. What the dev is such that just `npm install` some things and expect to work magically as he expected :D
