### ISSUE TITLE
How i can manually convert to buffer?

### ISSUE THREAD

**Issue by felixsanz** [helapkg/hela#75]
If i pass `buffer: true`, I have no problem, it works.

The problem is that i don't want all requests to be a buffer, so i removed the property and instead i'm doing `Buffer.from(ctx.request.body)` but i'm getting a different buffer instead.

Any idea why?

**Comment by felixsanz** [comment]
If if helps, i'm sending 267 bytes but i receive 258 bytes. Or at least thats what `console.log(ctx.request.body.length)` says (when not using `buffer:true`)

**Comment by tunnckoCore** [comment]
Hm.. nope, don't know. Not sure, but.. hm.

Can you give actual code and any other steps to try to reproduce it? What more requests you are expecting? I believe it can be hacked with little tricks through `extendTypes` and the other options. But I don't believe it is some implementation problem. More seems like a lack of imagination and architecture, haha just kidding.. lack of docs/recipes/examples/words - they are always welcome.

thanks for the feedback and report

**Comment by felixsanz** [comment]
@tunnckoCore You just have to:

```javascript
const Koa = require('koa')
const router = require('koa-router')()
const cors = require('koa-cors')
const body = require('koa-better-body')

const app = new Koa()

app.use(cors())
app.use(body())

router.post('/', async (ctx, next) => {
  console.log(ctx.request.body.length)
  await next()
})

app.use(router.routes())

app.listen(3000)
```

It prints 258. And i'm sending 267 bytes to the server.

The way i'm sending them is using an ajax request from the browser, and sending an Uint8Array() with raw bytes. 267 bytes in total.

It works just fine if i add `buffer:true` to the bodyparser, but what will affect all requests, which i don't want to.

Thanks! :tada:

**Comment by felixsanz** [comment]
Closed by mistake

**Comment by felixsanz** [comment]
You can't send a normal array over the wire :P An array is not a data structure outside of JS.

The Uint8Array is a representation of the binary data (byte by byte). It's a buffer basically.

I'll try to create a test case tomorrow but now i have to run! :tada:

**Comment by felixsanz** [comment]
@tunnckoCore I found the problem.

It's `tunnckoCore/body-parsers`: https://github.com/tunnckoCore/body-parsers/blob/master/index.js#L68

The encoding `utf8` is giving me a string of 258 bytes. If i remove that line, i get a buffer of 267 bytes, which is correct.

But as it is right now, that string is 258 bytes and i can't do `Buffer.from(string)` because it gives me a buffer of 258 bytes instead of the correct 267 bytes one.

Any idea on how i can overcome this?

**Comment by felixsanz** [comment]
Seems like you can't convert a compressed buffer into a string and then into a buffer again, so the solution is  use `buffer: true` or configure the middleware separately on each route instead of a global one :/

**Comment by tunnckoCore** [comment]
> The encoding utf8 is giving me a string of 258 bytes.
I thought for such shit :D 

One solution can be to PR to original `koa-body-parsers` to allow changing the encoding (or if you want you can send me a PR to that fork). I can't remember but there was a reason that I forked the original (because they didn't want some pr/feature)

> configure the middleware separately on each route instead of a global one

Much better.

**Comment by felixsanz** [comment]
A PR is not a good idea because it will break backwards compatibility.

I'll go the second option i guess xD

Thanks!

**Comment by tunnckoCore** [comment]
> break backwards compatibility.

it wont xD just the default would be `utf8` but it would be configurable not hardcoded as currently, but okey, good luck :)

**Comment by felixsanz** [comment]
But it should be:

`empty` -> no encoding, and works with buffer.
`utf8` -> utf8
etc -> etc

So basically i need the case where `empty` value or no value, doesn't add any encoding.

And right now, the `empty` case will trigger the default encoding of `utf8`.

So... removing the default value will break compatibility since people usually don't specify `utf8` manually, they omit the value and make use of the default, which is `utf8`. This people will now get a buffer instead of the expected `utf8` string. Thats why i claim that it will break compatibility but i may be wrong
