### ISSUE TITLE
Upgraded from v1 to v3 and got an "invalid urlencoded received" error

### ISSUE THREAD

**Issue by rockie** [helapkg/hela#76]
Recently just upgraded koa-better-body from v1.0.17 to the latest v3.0.2 and got an "invalid urlencoded received" error with below url pattern:
voucher?redirect_uri=%2Fdetail%2Fcixgpi5q60000bw20ghh50jcq
which is perfectly parsed in v1.0.17.

**Comment by tunnckoCore** [comment]
It's totally normal to have breaking changes. A lot of things was changed and are more better than ever.

Try to parse it using the internal `querystring` module. If it fails, that's the reason and so you should pass custom query parser (like `qs` package in npm) to options:

>
> - `querystring` {Object}: Querystring module to be used. By default builtin `querystring`.
> - `qs` {Object}: Alias of `opts.querystring`. All `opts` are also passed to `qs` or `querystring` module.
>

**Comment by distums** [comment]
Just encounter same problem, and it takes some time to figure out why.some documents would be helpful.

**Comment by tunnckoCore** [comment]
@rockie @distums The Changelog? And the whole Readme is full of docs and words, and examples? Plus, we also have some recipes, more are welcome!

**Comment by jeanru** [comment]
Have the same problem with this and fixed it by add following scripts in src/apps/index.js:
const qs = require('querystring')
app.querystring = qs
