### ISSUE TITLE
Conflict on ctx.querystring of koa2

### ISSUE THREAD

**Issue by wisdom-yzh** [helapkg/hela#77]
In koa2, ctx.querystring is equal to url search string.
for example, when i make a request such as:
curl -X POST 'http://localhost:3000/a/b?c=1&d=2' -d 'e=3&f=4'
ctx.querystring will be equal to 'c=1&d=2' and it is a string, not an object with method **parse**.
at last, module **koa-body-parsers** will throw error as below:
   this.ctx.throw(400, 'invalid urlencoded received')

so ctx.querystring below may be removed if koa-version is 2.0? 
 ctx.app.querystring = opts.querystring ||
   opts.qs || // alias
   ctx.app && ctx.app.querystring ||
   ctx.app && ctx.app.qs || // alias
   **ctx.querystring ||**
   ctx.qs // alias

**Comment by tunnckoCore** [comment]
Haha, yea - too many entry points. I was sure that it could make issues.
Thanks for the report.

**Comment by IceMimosa** [comment]
Any progress on this?

**Comment by tunnckoCore** [comment]
nope, i'm busy, but prs welcome.

**Comment by wisdom-yzh** [comment]
yet i have made a pr [https://github.com/tunnckoCore/koa-better-body/pull/84](https://github.com/tunnckoCore/koa-better-body/pull/84) to solve the problem simply

**Comment by jeanru** [comment]
Have the same problem with this and fixed it by add following scripts in src/apps/index.js:
const qs = require('querystring')
app.querystring = qs
